"""add defaults column to settings

Revision ID: 389bcfa5296b
Revises: 5ae435f83283
Create Date: 2013-11-28 18:15:55.215301

"""

# revision identifiers, used by Alembic.
revision = '389bcfa5296b'
down_revision = '5ae435f83283'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('defaults', sa.UnicodeText(), nullable=True))
    op.alter_column('app_settings', sa.Column('value', sa.UnicodeText(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'defaults')
    op.alter_column('app_settings', sa.Column('value', sa.Unicode(250), nullable=True))
    ### end Alembic commands ###
