"""Alter app_tickets table

Revision ID: 4f688c874891
Revises: 389bcfa5296b
Create Date: 2014-01-09 17:45:53.398494

"""

# revision identifiers, used by Alembic.
revision = '4f688c874891'
down_revision = '389bcfa5296b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    try:
        op.add_column('app_tickets', sa.Column('department_id', sa.Integer(), nullable=False))
        op.add_column('app_tickets', sa.Column('doctor_id', sa.Integer(), nullable=False))
        op.add_column('app_tickets', sa.Column('lpu_id', sa.Integer(), nullable=False))
    except Exception, e:
        print e
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_tickets', 'lpu_id')
    op.drop_column('app_tickets', 'doctor_id')
    op.drop_column('app_tickets', 'department_id')
    ### end Alembic commands ###
